[package]
name = "pascals-triangle"
version = "0.1.0"
authors = ["Parker McMullin <parker.mcmullin01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.2.0"
indoc = "1.0.1"
